apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-rollout
  namespace: test-namespace
spec:
  replicas: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 60
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 30 }
        - setWeight: 100
  selector:
    matchLabels:
      app: test-app-rollout
  template:
    metadata:
      labels:
        app: test-app-rollout
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 90 # Delays readiness
            periodSeconds: 5
          ports:
            - containerPort: 80
