apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: test-namespace
spec:
  replicas: 1
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: test-app-deployment
  template:
    metadata:
      labels:
        app: test-app-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 90 # Delays readiness
            periodSeconds: 5
          ports:
            - containerPort: 80
