apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-rollout
  namespace: test-namespace
spec:
  replicas: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 15
  strategy:
    canary: {}
  selector:
    matchLabels:
      app: test-app-rollout
  template:
    metadata:
      labels:
        app: test-app-rollout
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60 # Delays readiness
            periodSeconds: 5
          ports:
            - containerPort: 80
